const express = require("express");
const router = express.Router();
const reportController = require("../controllers/reportController");
const { protect } = require("../middleware/authMiddleware");

// Get all reports generated by the user
router.get("/", protect, reportController.getReports);

// Generate a new report
router.post("/", protect, reportController.generateReport);

// Delete a generated report
router.delete("/:id", protect, reportController.deleteReport);

// Download the generated report file
router.get("/:id/download", reportController.downloadReportFile);

module.exports = router;
